### PR TITLE
Move Portable csproj file into non-portable folder

### PR DESCRIPTION
**Pull request by kwhopper**
Use conditional compilation symbol to mark portable-specific changes.

### CODE REVIEW

**Comment by kwhopper** [comment]
Not sure on the appveyor failure. I have been using VS2015 - maybe that has something to do with it.

**Comment by kwhopper** [comment]
Fixed

**Comment by drewnoakes** [comment]
Thanks for this. I reworked it slightly and squashed the various commits to make the history easier to read and the delta simpler to observe.

Please review, and also note that I force-pushed master to include the last merged PR. You'll need to fetch and hard reset (or similar) your branch.

**Comment by kwhopper** [comment]
Very nice!

**Pull request closed without merging**
