### PR TITLE
Converted project to VS2017 csproj format

### PR DESCRIPTION
**Pull request by Tasteful**
After converted the project to the new csproj the `XmpCore.Tests` project was not compiled because of multiple entry points, that was fixed to move the extra program that not was a unit test into `XmpCore.Coverage`.

#26

### CODE REVIEW

**Comment by drewnoakes** [comment]
The coverage stuff should run with the test suite. It's the closest thing the Java XMPCore had to tests, at least that were publicly available. #30 solves this.

I hadn't considered that AssemblyInfo.cs is no longer needed when building this way. Is that truly the case? Very cool.

The current AppVeyor YAML is:

```yaml
version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: Release
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    cd XmpCore.Tests
    dotnet test
notifications:
- provider: Email
  to:
  - appveyor@drewnoakes.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
```

The coverage stuff breaks your PR, but that is a better approach. If you don't have time to update your PR I will take a look a bit later. Let me know.

**Comment by Tasteful** [comment]
I will update and fix the conflict.

**Comment by drewnoakes** [comment]
Wow, that was fast :) Thanks.

**Comment by Tasteful** [comment]
It was only an easy reabase on master that was needed to remove the files that not should be moved.

**Pull request merged**
