### PR TITLE
Add strong name signing in separate nuget package

### PR DESCRIPTION
**Pull request by Tasteful**
Alternative to the PR #24 that strong name signing all libraries. This PR creates a separate nuget-package that is strong name signed.

When running the `Build.cmd` all packages is created, test are run and artifacts are placed in the artifacts folder to upload directly to nuget.

### CODE REVIEW

**Comment by drewnoakes** [comment]
One difference here is that `msbuild` doesn't produce a symbols package, which `dotnet pack` did. I'm not sure it's a huge problem, but if you know a simple way to get symbols from `msbuild` too...

**Comment by Tasteful** [comment]
Do you want the pdb in the same package or in an symbol package?

**Comment by drewnoakes** [comment]
The current `.nupkg` is fine as is -- with DLL and XML.

What used to be produced was another `.symbols.nupkg` file with the same prefix, that contained DLL, XML, PDB and source code. This would be automatically uploaded by `nuget.exe` to Microsoft symbol server and could be downloaded by users in Visual Studio (and possibly other IDEs).

**Comment by drewnoakes** [comment]
Here's an example: [XmpCore.2.0.1.symbols.nupkg.zip](https://github.com/drewnoakes/xmp-core-dotnet/files/847653/XmpCore.2.0.1.symbols.nupkg.zip)

**Comment by drewnoakes** [comment]
Pushed 5.1.3.0 to NuGet, including the strongly named variant.

**Pull request closed without merging**
