### PR TITLE
Sign with a keyFile. Implies a strong name.

### PR DESCRIPTION
**Pull request by kwhopper**
#11 

This builds in XmpCore with no other changes and executes. Whoever needed this signed and has the means to build my branch, it would be great if you would test. It's a bit of a catch-22 but it seems safe, and is easy enough to get rid of if necessary. Otherwise, this is step one to getting metadata-extractor-dotnet signed as well.

@drewnoakes  - Referenced assemblies of a signed (strong name) assembly have to be signed as well so the nuget package will have to be updated and referenced in MED before any further changes there. It shouldn't matter that XmpCore is signed and MED is not. The other way around (MED signed, XmpCore not) is what doesn't work. I haven't done this before however, but others ([Dapper](https://www.nuget.org/packages/Dapper/) was mentioned) have done it with only a SNK file. While Dapper is currently two projects, they intend to merge them into a signed-only version for 2.0 - [https://github.com/StackExchange/Dapper/issues/498](https://github.com/StackExchange/Dapper/issues/498) towards the end.

### CODE REVIEW

**Comment by kwhopper** [comment]
Also, I updated the version to 5.1.3 on purpose but please review. There might be less confusion that way since the assembly is otherwise unchanged and a version difference makes it obvious.

**Comment by kwhopper** [comment]
Further reading:

http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html

Redis (https://github.com/StackExchange/StackExchange.Redis) continues to offer two builds/nuget versions with and without a strong name. I'm fine either way if you would rather have different versions to keep any SNK problems localized. It could be done the same way with metadata-extractor-dotnet also but we have to decide on XmpCore first to proceed.

**Comment by drewnoakes** [comment]
Thanks for this PR.

I'm still not 100% sure what the best approach is here. I am sympathetic to those who need strongly named assemblies, however rare the need, but they are a bit of a pain.

One concern I have is that the key shouldn't really be in the repository. As I understand it, the primary purpose of strong naming is to verify that loaded code is trustworthy. If the key is available to anyone, then it's possible to load arbitrary code into an environment that's trying to prevent that. If the key is kept private, then it'd be kept by a few project members and used for signing NuGet packages.

I haven't yet read the articles you've linked to and unfortunately won't have time to do so for a few days.

**Comment by kwhopper** [comment]
No keys or passwords were used to make the SNK in this PR, so all it does is allow a strong name. I'm torn on this whole idea as well. In the 'pro' column, I think open source development is using (in this case) the nuget package URL as the "real" trustworthy authority, as log4net illustrates:

https://svn.apache.org/repos/asf/logging/log4net/trunk/log4net.snk.readme

When the code is already public and can be compiled by anyone anyway, it seems somewhat irrelevant to care whether a SNK file is in the source.

OTOH, the 'con' side has a legitimate source of pain that involves purposely (or inadvertently) changing the strong name and not updating the version numbers correctly:

http://haacked.com/archive/2012/02/16/changing-a-strong-name-is-a-major-breaking-change.aspx/

More thought on this leads me to think if we support this scenario it should be as a separate project and nuget package. That may be more trouble than it's worth when the few people who want it signed could potentially do exactly what this PR does with a free version of VS.

**Comment by kwhopper** [comment]
Sorry - one more in an effort catalog all the pros and cons:

https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md#faq

**Comment by kwhopper** [comment]
Here are two utilities that make it reasonable to NOT sign your projects:

https://github.com/dsplaisted/strongnamer
https://github.com/brutaldev/StrongNameSigner

Anyone that needs strong names could pretty easily do it with these, I think.

**Comment by Tasteful** [comment]
I'm one of the person that need the library signed (reson exists in the comment here https://github.com/drewnoakes/xmp-core-dotnet/issues/11) and it is more practical that the original package author that is releasing the original package also building an signed version instead that it will be a delay before some third party person updating the package. 

I don't say that you need to sign your package but if you decide to not sign the current package, can use make a signed package also?

It is easy to setup a new project that will use the same source files as the unsigned one and building that on the same time, the result will be 2 package with different names. One signed and one unsigned. I was doing that for the https://github.com/AutoMapper/AutoMapper.Collection/tree/master/src/AutoMapper.Collection-Signed so that is producing one extra package that can be published to nuget.

For thrustworthy, authenticode signing is used (certificate based); on the downloaded dll you can check the properties on the file and see author in the Digital Signatures tab.

**Comment by Tasteful** [comment]
I added the alternative way with adding the strong name assemblies with separate name, se linked PR.

**Comment by drewnoakes** [comment]
Thanks @kwhopper for your research into this. Seems the problem is solved.

**Pull request closed without merging**
